---
- name: Install and start Nginx on an Azure virtual machine
  hosts: all
  become: yes
  pre_tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  tasks:
  - name: install nginx
    apt: pkg=nginx state=installed update_cache=true
    notify:
    - start nginx
  - name: index.html copy
    template: src=welcome.html.j2 dest=/usr/share/nginx/html/index.html

  handlers:
    - name: start nginx
      service: name=nginx state=started
